version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      url-extractors:
        patterns:
          - "yt-dlp*"
          - "gallery-dl"
      python-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "yt-dlp*"
          - "gallery-dl"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "python"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "github-actions"
